### ISSUE TITLE
not working some websites

### ISSUE THREAD

**Issue by heissonly** [emres/turkish-deasciifier#15]
I don't understand why but it is not working some websites (for example web.whatsapp.com).

**Comment by emres** [comment]
Hello,

This is a Python package and is not intended to be integrated with any web site. Did you mean the JavaScript version (Firefox add-on, etc.) by chance?

**Comment by heissonly** [comment]
Yes,sorry you are right, the problem is about javascript version.(chrome extension) I should have written there. Can you copy a link of this repository if you know .

**Comment by emres** [comment]
The only Chrome extension I know is hosted at https://github.com/meacer/deasciifier . You can contact the developers of that repository.
