### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by Orkin31** [emres/turkish-deasciifier#3]
Merhaba.

`pip install git+https://github.com/emres/turkish-deasciifier.git` yaptığımda

```
ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-req-build-nl97thly\setup.py", line 62
        except OSError, e:
                      ^
    SyntaxError: invalid syntax


```

erroru alıyorum. setup dosyasında sorun var sanırım

**Comment by emres** [comment]
Merhaba,

Sanırım problemin kaynağı şu adrestekine benzer bir durum: 

- https://stackoverflow.com/a/20517801/236007

Başka bir deyişle, `except OSError, e` yerine `except OSError as e` yazmak problemi çözebilir.

Şu anda maalesef çok vaktim yok ama siz benim kod deposunu "fork" edip, kendi "fork" ettiğiniz depoda bahsettiğim değişikliği yapıp, bu değişikliği içeren kendi deponuzu kullanarak benzer bir `pip install` testi yapıp çalıştığından emin olursanız bana bir Pull Request gönderebilirsiniz GitHub üzerinden, böylece ben de bu değişikliği ekleyebilirim sisteme kolayca.

**Comment by emres** [comment]
Ek açıklama: yukarıda verilmiş olan bağlantıda üstü örtülü olarak belirtilmiş ama açıkça yazalım, problem Python 2'de geçerli olan söz diziminin Python 3'te kabul görmemesi: 

- https://www.python.org/dev/peps/pep-3110/#grammar-changes

Ve:

- https://docs.python.org/2/whatsnew/2.6.html#pep-3110-exception-handling-changes

> Python 3.0 will only support the use of “as”, and therefore interprets the first example as catching two different exceptions. Python 2.6 supports both the comma and “as”, so existing code will continue to work. We therefore suggest using “as” when writing new Python code that will only be executed with 2.6.

Yani sizin ortamınızda varsayılan ('default') Python versiyonu 3.x serisi ise, bu problem ortaya çıkıyor.

**Comment by Orkin31** [comment]
Python3 ile çelişen kodları Python3'e çevirerek durumu düzelttim. Pull request yolladım.

**Comment by emres** [comment]
Vakit ayırıp katkıda bulunduğunuz için çok teşekkürler! "Pull Request"i test ettim ve kabul ettim, `pip install git+https://github.com/emres/turkish-deasciifier.git` düzgün çalışıyor. 

Ayrıca README.md'ye Python 3 örneği eklediğiniz için teşekkürler!
