### ISSUE TITLE
PDF desteği gelsin

### ISSUE THREAD

**Issue by lilcsz** [emres/turkish-deasciifier#9]

**Comment by emres** [comment]
Merhaba @lilcsz,

PDF desteği ile kast ettiğin tam olarak nedir? Girdi olarak sistemin PDF dosyalarını da kabul etmesi mi, yoksa çıktı olarak PDF dosya da üretmesi mi?

**Comment by lilcsz** [comment]
PDF Dosyalarını kabul etmesi

**Comment by emres** [comment]
@lilcsz, böyle bir özellik bu programın kapsamı dışında kalıyor. PDF biçiminde bir dosyayı, [pdfminer.six](https://pdfminersix.readthedocs.io/en/latest/) ya da [pdftotext](https://www.xpdfreader.com/about.html) gibi bir programdan geçirip metin (text) çıktıyı [turkish-deasciifier](https://github.com/emres/turkish-deasciifier)'a yönlendirmek pratik bir çözüm olacaktır.
